name: flutter_map_demo
description: A Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_map: 0.6.1+2
  camera: 0.5.2+1
  path_provider: ^0.5.0+1
  path: 1.6.2
  sqflite: 1.1.6+3
  provider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - secrets.json